<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="content-type" content="text/html">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>填写订单</title>
    <meta name="keywords" content="">
    <meta name="description" content="">
    <link rel="stylesheet" href="/public/css/base.css">
    <link rel="stylesheet" href="/public/css/public.css">
    <link rel="stylesheet" href="/public/css/order.css">
</head>
<body>
    <!--    公共头部    -->
    <?php load_view("inc/header");?>

    <!--     content     -->
    <div class="container">
        <!--  进度条  -->
        <div class="forget_guide pr">
            <span class="forget_one dib active">1.填写订单</span>
            <span class="forget_two dib">2.支付订单</span>
            <span class="forget_three dib">3.领取资料</span>
            <span class="forget_four dib">4.交易成功</span>
        </div>
        <p class="seller_title">您购买的商品信息</p>
        <div class="info_box cf">
            <i class="fl"></i>
            <div class="fl">
                <p class="title ofh">【风暴骑兵 女 90级 QQ等级11-20级 无QQ好友 不存在5天封号记录 】★大象专卖★天空套，攻城炮恍惚万世三神器</p>
                <p class="title ofh">商品类型：帐号</p>
                <p class="title ofh">所在区/服：地下城与勇士/ 腾讯/ 广东区/广东6区/</p>
            </div>
        </div>
        <p class="public_title">联系方式</p>
        <div class="account">
            <div class="iphone"><span>您的手机号：</span><input type="number" placeholder="176****0262"></div>
            <div class="qq"><span>您的&nbsp;QQ号：</span><input type="number" placeholder="请输入您的QQ号码"></div>
        </div>
        <p class="public_title">确认提交订单</p>
        <div class="amount">
            <p class="pay">应付款：<span class="money">199.00</span> 元</p>
            <a class="sub_btn" href="/Order/pay?type=index">确认无误，点击购买</a>
        </div>
    </div>

    <!--    底部公共    -->
    <?php load_view("inc/footer");?>

    <script src="/public/js/jquery.js"></script>
    <script src="/public/js/public.js"></script>
</body>
</html>