<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="content-type" content="text/html">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>领取资料</title>
    <meta name="keywords" content="">
    <meta name="description" content="">
    <link rel="stylesheet" href="/public/css/base.css">
    <link rel="stylesheet" href="/public/css/public.css">
    <link rel="stylesheet" href="/public/css/order.css">
</head>
<body>
    <!--    公共头部    -->
    <?php load_view("inc/header");?>

    <!--    content    -->
    <div class="container">
        <!--  进度条  -->
        <div class="forget_guide pr">
            <span class="forget_one dib active">1.填写订单</span>
            <span class="forget_two dib active">2.支付订单</span>
            <span class="forget_three dib active">3.领取资料</span>
            <span class="forget_four dib">4.交易成功</span>
        </div>
        <p class="seller_title">完成订单&nbsp;&nbsp;<span class="sure">订单已支付完成</span></p>
        <div class="info_box cf">
            <i class="fl"></i>
            <div class="fl">
                <p class="title ofh">【风暴骑兵 女 90级 QQ等级11-20级 无QQ好友 不存在5天封号记录 】★大象专卖★天空套，攻城炮恍惚万世三神器</p>
                <p class="title ofh">商品类型：帐号</p>
                <p class="title ofh">所在区/服：地下城与勇士/ 腾讯/ 广东区/广东6区/</p>
                <p class="title ofh">订单号：DB20180903602736036</p>
                <p class="title ofh">购买时间：2018年09月03日 16:44:33</p>
                <p class="title ofh">支付金额：199.00</p>
            </div>
        </div>
        <p class="public_title">领取资料</p>
        <div class="account">
            <div class="iphone"><span>您购买的玩家账号：</span><input type="number" placeholder="17688830262" readonly="readonly"></div>
            <div class="qq"><span>您购买的玩家密码：</span><input type="number" placeholder="12345678" readonly="readonly"></div>
        </div>
        <a class="sub_btn receive_btn" href="/Order/complete?type=index">确认无误，点击领取</a>

    </div>

    <!--    底部公共    -->
    <?php load_view("inc/footer");?>

    <script src="/public/js/jquery.js"></script>
    <script src="/public/js/public.js"></script>
</body>
</html>