<?php error_reporting(0); ?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="content-type" content="text/html">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>404页面不存在</title>
    <meta name="keywords" content="">
    <meta name="description" content="">
    <meta http-equiv="Refresh" content="3; url=http://shop.zhishengwh.com" />
    <link rel="stylesheet" href="/public/css/base.css">
    <link rel="stylesheet" href="/public/css/public.css">
</head>
<body>
<!--    公共头部    -->
<?php load_view("inc/header");?>

<!--    404    -->
<div class="container" style="text-align: center;margin-top: 100px;">
    <img class="dib" src="/public/images/common/no_some.png" height="102" width="96" style="vertical-align: middle;margin-right: 20px;" alt="">
    <span style="font-size: 30pt;color: #FFE8CD;vertical-align: middle;">404页面不存在</span>
</div>

</body>
</html>