<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="content-type" content="text/html">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>常见问题</title>
    <meta name="keywords" content="">
    <meta name="description" content="">
    <link rel="stylesheet" href="/public/css/base.css">
    <link rel="stylesheet" href="/public/css/public.css">
    <link rel="stylesheet" href="/public/css/buy_guide.css">
</head>
<body>
<!--    公共头部    -->
<?php load_view("inc/ucheader");?>
<!--     content     -->
<div class="container">
    <!--   面包屑   -->
    <div class="crumbs">您的位置：<span>首页 ></span><span> 个人中心</span></div>
    <div class="uc_box cf">
        <?php load_view("inc/ucleft");?>
        <div class="uc_right fr">
            <p class="guide_title">常见问题</p>
            <ul class="guide_ul">
                <li class="copy" data-num="10">
                    <p><span>问：</span><span>我发布的商品多久审核时间才能上线？</span></p>
                    <p><span>答：</span><span>我们会在订单生成后，经过玩转平台人工智能审核后，没有问题一般两个小时后通过展示在玩转平台中，敬请期待。</span></p>
                </li>
            </ul>
            <div style="text-align: center;padding: 30px 0;">分页BOX</div>
        </div>
    </div>
</div>

<script src="/public/js/jquery.js"></script>
<script src="/public/js/public.js"></script>
</body>
</html>