<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="content-type" content="text/html">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>修改密码</title>
    <meta name="keywords" content="">
    <meta name="description" content="">
    <link rel="stylesheet" href="/public/css/base.css">
    <link rel="stylesheet" href="/public/css/public.css">
    <link rel="stylesheet" href="/public/css/modifypwd.css">
</head>
<body class="homeMain">
    <!--    公共头部    -->
    <?php load_view("inc/ucheader");?>
    <!--     content     -->
    <div class="container">
        <!--   面包屑   -->
        <div class="crumbs">您的位置：<span>首页 ></span><span> 个人中心</span></div>
        <div class="uc_box cf">

            <?php load_view("inc/ucleft");?>
            
            <div class="uc_right fr">
                <div class="buy_title"><span>修改密码</span></div>
                <p class="cf">
                    <span class="order_text fl">当前账号：</span>
                    <span class="pwd_name">17688830262</span>
                </p>
                <div class="user_time cf">
                    <p class="cf">
                        <span class="order_text fl">真实姓名：</span>
                        <input class="user_search fl" type="text" name="" placeholder="例如：黄帅哥">
                    </p>
                    <p class="cf">
                        <span class="order_text fl">身份证号：</span>
                        <input class="user_search fl" type="text" name="" placeholder="4600**********1234">
                    </p>
                </div>
                <div class="user_time cf hide">
                    <p class="cf">
                        <span class="order_text fl">新的密码：</span>
                        <input class="user_search fl" type="text" name="" placeholder="例如：黄帅哥">
                    </p>
                    <p class="cf">
                        <span class="order_text fl">确认密码：</span>
                        <input class="user_search fl" type="text" name="" placeholder="4600**********1234">
                    </p>
                </div>
                <div class="sub_form_box"><input class="submit_input" type="submit" value="下一步"></div>
            </div>
        </div>
    </div>

    <script src="/public/js/jquery.js"></script>
    <script src="/public/js/public.js"></script>
    <script src="/public/js/collection.js"></script>
</body>
</html>