<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="content-type" content="text/html">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>商品交易</title>
    <meta name="keywords" content="">
    <meta name="description" content="">
    <link rel="stylesheet" href="/public/css/base.css">
    <link rel="stylesheet" href="/public/css/public.css">
    <link rel="stylesheet" href="/public/css/index.css">
</head>
<body class="homeMain">

<?php load_view("inc/header");?>
<!--     content     -->
<div class="content_box container">

    <!--    金币交易头部    -->
    <div class="trade_box" style="margin-top: 20px;">
        <img src="/public/images/index/wine_bg.png" width="1200" height="500" alt="">
    </div>

    <!--      红酒兑换      -->
    <div class="recommend">
        <div class="broadcast_title cf"><p class="fl pr">红酒兑换<span class="line_l"></span></p></div>
        <ul class="broadcast_ul recommend_ul cf">
            <li class="fl pr"><a class="li_a" href="/Index/shopdetails?type=goods"><p class="text_c"><img class="dib" src="/public/images/index/shop.png" alt=""></p><p class="re_text ofh">1919酒类直供奔富BIN407解 百纳赤霞珠红葡萄酒 红酒</p><p class="re_money ofh">658平台币</p><p class="re_stock ofh">剩余库存：188支</p></a><a class="ex_a" href="javascript:void(0);">立即兑换</a></li>
            <li class="fl pr"><a class="li_a" href="/Index/shopdetails?type=goods"><p class="text_c"><img class="dib" src="/public/images/index/shop.png" alt=""></p><p class="re_text ofh">1919酒类直供奔富BIN407解 百纳赤霞珠红葡萄酒 红酒</p><p class="re_money ofh">658平台币</p><p class="re_stock ofh">剩余库存：188支</p></a><a class="ex_a" href="javascript:void(0);">立即兑换</a></li>
            <li class="fl pr"><a class="li_a" href="/Index/shopdetails?type=goods"><p class="text_c"><img class="dib" src="/public/images/index/shop.png" alt=""></p><p class="re_text ofh">1919酒类直供奔富BIN407解 百纳赤霞珠红葡萄酒 红酒</p><p class="re_money ofh">658平台币</p><p class="re_stock ofh">剩余库存：188支</p></a><a class="ex_a" href="javascript:void(0);">立即兑换</a></li>
            <li class="fl pr"><a class="li_a" href="/Index/shopdetails?type=goods"><p class="text_c"><img class="dib" src="/public/images/index/shop.png" alt=""></p><p class="re_text ofh">1919酒类直供奔富BIN407解 百纳赤霞珠红葡萄酒 红酒</p><p class="re_money ofh">658平台币</p><p class="re_stock ofh">剩余库存：188支</p></a><a class="ex_a" href="javascript:void(0);">立即兑换</a></li>
        </ul>
    </div>
    <!--      白酒兑换      -->
    <div class="recommend">
        <div class="broadcast_title cf"><p class="fl pr">白酒兑换<span class="line_l"></span></p></div>
        <ul class="broadcast_ul recommend_ul cf">
            <li class="fl pr"><a class="li_a" href="/Index/shopdetails?type=goods"><p class="text_c"><img class="dib" src="/public/images/index/shop3.png" alt=""></p><p class="re_text ofh">1919酒类直供奔富BIN407解 百纳赤霞珠红葡萄酒 红酒</p><p class="re_money ofh">658平台币</p><p class="re_stock ofh">剩余库存：188支</p></a><a class="ex_a" href="javascript:void(0);">立即兑换</a></li>
            <li class="fl pr"><a class="li_a" href="/Index/shopdetails?type=goods"><p class="text_c"><img class="dib" src="/public/images/index/shop3.png" alt=""></p><p class="re_text ofh">1919酒类直供奔富BIN407解 百纳赤霞珠红葡萄酒 红酒</p><p class="re_money ofh">658平台币</p><p class="re_stock ofh">剩余库存：188支</p></a><a class="ex_a" href="javascript:void(0);">立即兑换</a></li>
            <li class="fl pr"><a class="li_a" href="/Index/shopdetails?type=goods"><p class="text_c"><img class="dib" src="/public/images/index/shop3.png" alt=""></p><p class="re_text ofh">1919酒类直供奔富BIN407解 百纳赤霞珠红葡萄酒 红酒</p><p class="re_money ofh">658平台币</p><p class="re_stock ofh">剩余库存：188支</p></a><a class="ex_a" href="javascript:void(0);">立即兑换</a></li>
            <li class="fl pr"><a class="li_a" href="/Index/shopdetails?type=goods"><p class="text_c"><img class="dib" src="/public/images/index/shop3.png" alt=""></p><p class="re_text ofh">1919酒类直供奔富BIN407解 百纳赤霞珠红葡萄酒 红酒</p><p class="re_money ofh">658平台币</p><p class="re_stock ofh">剩余库存：188支</p></a><a class="ex_a" href="javascript:void(0);">立即兑换</a></li>
        </ul>
    </div>
    <!--      钻石兑换      -->
    <div class="recommend">
        <div class="broadcast_title cf"><p class="fl pr">钻石兑换<span class="line_l"></span></p></div>
        <ul class="broadcast_ul recommend_ul cf">
            <li class="fl pr"><a class="li_a" href="/Index/shopdetails?type=goods"><p class="text_c"><img class="dib" src="/public/images/index/shop2.png" alt=""></p><p class="re_text ofh">1919酒类直供奔富BIN407解 百纳赤霞珠红葡萄酒 红酒</p><p class="re_money ofh">658平台币</p><p class="re_stock ofh">剩余库存：188支</p></a><a class="ex_a" href="javascript:void(0);">立即兑换</a></li>
            <li class="fl pr"><a class="li_a" href="/Index/shopdetails?type=goods"><p class="text_c"><img class="dib" src="/public/images/index/shop2.png" alt=""></p><p class="re_text ofh">1919酒类直供奔富BIN407解 百纳赤霞珠红葡萄酒 红酒</p><p class="re_money ofh">658平台币</p><p class="re_stock ofh">剩余库存：188支</p></a><a class="ex_a" href="javascript:void(0);">立即兑换</a></li>
            <li class="fl pr"><a class="li_a" href="/Index/shopdetails?type=goods"><p class="text_c"><img class="dib" src="/public/images/index/shop2.png" alt=""></p><p class="re_text ofh">1919酒类直供奔富BIN407解 百纳赤霞珠红葡萄酒 红酒</p><p class="re_money ofh">658平台币</p><p class="re_stock ofh">剩余库存：188支</p></a><a class="ex_a" href="javascript:void(0);">立即兑换</a></li>
            <li class="fl pr"><a class="li_a" href="/Index/shopdetails?type=goods"><p class="text_c"><img class="dib" src="/public/images/index/shop2.png" alt=""></p><p class="re_text ofh">1919酒类直供奔富BIN407解 百纳赤霞珠红葡萄酒 红酒</p><p class="re_money ofh">658平台币</p><p class="re_stock ofh">剩余库存：188支</p></a><a class="ex_a" href="javascript:void(0);">立即兑换</a></li>
        </ul>
    </div>
</div>

<?php load_view("inc/footer");?>

<script src="/public/js/gold.js"></script>
</body>
</html>