<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="content-type" content="text/html">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>兑换中心首页</title>
    <meta name="keywords" content="">
    <meta name="description" content="">
    <link rel="stylesheet" href="/public/css/swiper-4.3.3.min.css">
    <link rel="stylesheet" href="/public/css/base.css">
    <link rel="stylesheet" href="/public/css/public.css">
    <link rel="stylesheet" href="/public/css/index.css">
</head>
<body class="homeMain">

    <?php load_view("inc/header");?>

    <div class="content_box container">
        <!--     轮播图     -->
        <div class="s_banner slide-box pr">
            <ul class="slide-content">
                <li><a href="javascript:void(0);" target="_blank" title=""><img src="/public/images/banner/banner1.png" alt=""></a></li>
                <li><a href="javascript:void(0);" target="_blank" title=""><img src="/public/images/banner/banner2.png" alt=""></a></li>
                <li><a href="javascript:void(0);" target="_blank" title=""><img src="/public/images/banner/banner3.png" alt=""></a></li>
                <li><a href="javascript:void(0);" target="_blank" title=""><img src="/public/images/banner/banner4.png" alt=""></a></li>
                <li><a href="javascript:void(0);" target="_blank" title=""><img src="/public/images/banner/banner5.png" alt=""></a></li>
            </ul>
            <ol class="slide-triggers">
                <li></li>
                <li></li>
                <li></li>
                <li></li>
                <li></li>
            </ol>
        </div>

        <!--    热门游戏、我要购买、我要卖出    -->
        <div class="hot_box cf">
            <div class="hot_left fl">
                <div class="title_box cf">
                    <p class="tit_name fl">热门游戏</p>
                    <a class="more_link fr" href="/Index/more?type=index"><span>更多</span></a>
                </div>
                <ul class="hot_ul cf">
                    <?php foreach ($arrData as $key=>$value):?>
                    <li class="fl">
                        <a href="/List/index?type=index&apkname=<?=$value['title']?>&shoptype=all">
                            <img src="http://www.zhishengwh.com/uploads/<?=$value['icon']?>" width="120" height="120" alt="<?=$value['info']?>">
                            <p class="ofh"><?=$value['title']?></p>
                        </a>
                    </li>
                    <?php endforeach;?>
                </ul>
            </div>
            <div class="hot_right fr">
                <ul class="btn_ul cf">
                    <li class="buy_li fl"><a class="cf" href="/List/allindex?type=index"><i class="fl"></i><p class="fl">我要买</p></a></li>
                    <li class="sell_li fr"><a class="cf" href="/Uc/productrelease"><i class="fl"></i><p class="fl">我要卖</p></a></li>
                </ul>
                <ul class="service_ul cf">
                    <li class="guide_li fl"><a class="cf" href="/Uc/buyguide?type=buyguide"><i></i><p>购买指南</p></a></li>
                    <li class="release_li fl"><a class="cf" href="/Uc/releaseguide?type=releaseguide"><i></i><p>发布指南</p></a></li>
                    <li class="server_li fl"><a class="cf" href="/Uc/commonproblem?type=commonproblem"><i></i><p>常见问题</p></a></li>
                </ul>
                <!--  广告位  -->
                <div class="ad"><a href="http://www.zhishengwh.com/" target="_blank" style="display: block;"><img src="/public/images/index/ad.png" alt=""></a></div>
                <div class="notice">
                    <div class="n_title"><p>公告</p></div>
                    <ul class="n_ul">
                        <?php foreach ($newData as $k=>$v): ?>
                        <li class="copy">
                            <a class="cf" href="http://www.zhishengwh.com/newsinfo?type=index&id=<?=$v['id']?>">
                                <p class="n_text ofh fl"><?=$v['title']?></p>
                                <span class="n_date fr"><?=date('m-d',$v['create_time'])?></span>
                            </a>
                        </li>
                        <?php endforeach; ?>
                    </ul>
                </div>
            </div>
        </div>

        <!--     性价比推荐     -->
        <div class="broadcast_box">
            <div class="broadcast_title cf"><p class="fl pr">性价比推荐<span class="line_l"></span></p><a class="fr" href="javascript:void(0);">更多</a></div>
            <ul class="broadcast_ul cf">
                <li class="fl">
                    <div class="slide-box swiper-container">
                        <div class="swiper-wrapper">
                            <div class="swiper-slide">
                                <a href="#">
                                    <p class="s_name">金币交易</p>
                                    <p class="s_title ofh">魔兽世界</p>
                                    <p class="s_text ofh">【当面交易】2260万金币=43元</p>
                                    <p class="s_text1 ofh">【在线发货，方便快捷】</p>
                                    <p class="s_exp ofh">1元=2857.14金游戏币</p>
                                    <img src="/public/images/index/game_bar.png" width="140" height="140" alt="">
                                </a>
                            </div>
                            <div class="swiper-slide">
                                <a href="#">
                                    <p class="s_name">金币交易</p>
                                    <p class="s_title ofh">魔兽世界</p>
                                    <p class="s_text ofh">【当面交易】2260万金币=43元</p>
                                    <p class="s_text1 ofh">【在线发货，方便快捷】</p>
                                    <p class="s_exp ofh">1元=2857.14金游戏币</p>
                                    <img src="/public/images/index/game_bar.png" width="140" height="140" alt="">
                                </a>
                            </div>
                            <div class="swiper-slide">
                                <a href="#">
                                    <p class="s_name">金币交易</p>
                                    <p class="s_title ofh">魔兽世界</p>
                                    <p class="s_text ofh">【当面交易】2260万金币=43元</p>
                                    <p class="s_text1 ofh">【在线发货，方便快捷】</p>
                                    <p class="s_exp ofh">1元=2857.14金游戏币</p>
                                    <img src="/public/images/index/game_bar.png" width="140" height="140" alt="">
                                </a>
                            </div>
                            <div class="swiper-slide">
                                <a href="#">
                                    <p class="s_name">金币交易</p>
                                    <p class="s_title ofh">魔兽世界</p>
                                    <p class="s_text ofh">【当面交易】2260万金币=43元</p>
                                    <p class="s_text1 ofh">【在线发货，方便快捷】</p>
                                    <p class="s_exp ofh">1元=2857.14金游戏币</p>
                                    <img src="/public/images/index/game_bar.png" width="140" height="140" alt="">
                                </a>
                            </div>
                        </div>
                        <!-- 如果需要分页器 -->
                        <div class="swiper-pagination"></div>
                        <!-- 如果需要导航按钮 -->
                        <div class="swiper-button-prev"></div>
                        <div class="swiper-button-next"></div>
                    </div>
                </li>
                <li class="fl">
                    <div class="slide-box swiper-container">
                        <div class="swiper-wrapper">
                            <div class="swiper-slide">
                                <a href="#">
                                    <p class="s_name s_name1">账号交易</p>
                                    <p class="s_title ofh">魔兽世界</p>
                                    <p class="s_text ofh">【当面交易】2260万金币=43元</p>
                                    <p class="s_text1 ofh">【在线发货，方便快捷】</p>
                                    <p class="s_exp ofh">1元=2857.14金游戏币</p>
                                    <img src="/public/images/index/game_bar.png" width="140" height="140" alt="">
                                </a>
                            </div>
                            <div class="swiper-slide">
                                <a href="#">
                                    <p class="s_name s_name1">账号交易</p>
                                    <p class="s_title ofh">魔兽世界</p>
                                    <p class="s_text ofh">【当面交易】2260万金币=43元</p>
                                    <p class="s_text1 ofh">【在线发货，方便快捷】</p>
                                    <p class="s_exp ofh">1元=2857.14金游戏币</p>
                                    <img src="/public/images/index/game_bar.png" width="140" height="140" alt="">
                                </a>
                            </div>
                            <div class="swiper-slide">
                                <a href="#">
                                    <p class="s_name s_name1">账号交易</p>
                                    <p class="s_title ofh">魔兽世界</p>
                                    <p class="s_text ofh">【当面交易】2260万金币=43元</p>
                                    <p class="s_text1 ofh">【在线发货，方便快捷】</p>
                                    <p class="s_exp ofh">1元=2857.14金游戏币</p>
                                    <img src="/public/images/index/game_bar.png" width="140" height="140" alt="">
                                </a>
                            </div>
                            <div class="swiper-slide">
                                <a href="#">
                                    <p class="s_name s_name1">账号交易</p>
                                    <p class="s_title ofh">魔兽世界</p>
                                    <p class="s_text ofh">【当面交易】2260万金币=43元</p>
                                    <p class="s_text1 ofh">【在线发货，方便快捷】</p>
                                    <p class="s_exp ofh">1元=2857.14金游戏币</p>
                                    <img src="/public/images/index/game_bar.png" width="140" height="140" alt="">
                                </a>
                            </div>
                        </div>
                        <!-- 如果需要分页器 -->
                        <div class="swiper-pagination"></div>
                        <!-- 如果需要导航按钮 -->
                        <div class="swiper-button-prev"></div>
                        <div class="swiper-button-next"></div>
                    </div>
                </li>
                <li class="fl">
                    <div class="slide-box swiper-container">
                        <div class="swiper-wrapper">
                            <div class="swiper-slide">
                                <a href="#">
                                    <p class="s_name s_name2">装备交易</p>
                                    <p class="s_title ofh">魔兽世界</p>
                                    <p class="s_text ofh">【当面交易】2260万金币=43元</p>
                                    <p class="s_text1 ofh">【在线发货，方便快捷】</p>
                                    <p class="s_exp ofh">1元=2857.14金游戏币</p>
                                    <img src="/public/images/index/game_bar.png" width="140" height="140" alt="">
                                </a>
                            </div>
                            <div class="swiper-slide">
                                <a href="#">
                                    <p class="s_name s_name2">装备交易</p>
                                    <p class="s_title ofh">地下城与勇士</p>
                                    <p class="s_text ofh">【当面交易】2260万金币=43元</p>
                                    <p class="s_text1 ofh">【在线发货，方便快捷】</p>
                                    <p class="s_exp ofh">1元=2857.14金游戏币</p>
                                    <img src="/public/images/index/game_bar.png" width="140" height="140" alt="">
                                </a>
                            </div>
                            <div class="swiper-slide">
                                <a href="#">
                                    <p class="s_name s_name2">装备交易</p>
                                    <p class="s_title ofh">魔兽世界</p>
                                    <p class="s_text ofh">【当面交易】2260万金币=43元</p>
                                    <p class="s_text1 ofh">【在线发货，方便快捷】</p>
                                    <p class="s_exp ofh">1元=2857.14金游戏币</p>
                                    <img src="/public/images/index/game_bar.png" width="140" height="140" alt="">
                                </a>
                            </div>
                            <div class="swiper-slide">
                                <a href="#">
                                    <p class="s_name s_name2">装备交易</p>
                                    <p class="s_title ofh">魔兽世界</p>
                                    <p class="s_text ofh">【当面交易】2260万金币=43元</p>
                                    <p class="s_text1 ofh">【在线发货，方便快捷】</p>
                                    <p class="s_exp ofh">1元=2857.14金游戏币</p>
                                    <img src="/public/images/index/game_bar.png" width="140" height="140" alt="">
                                </a>
                            </div>
                        </div>
                        <!-- 如果需要分页器 -->
                        <div class="swiper-pagination"></div>
                        <!-- 如果需要导航按钮 -->
                        <div class="swiper-button-prev"></div>
                        <div class="swiper-button-next"></div>
                    </div>
                </li>
                <li class="fl">
                    <div class="slide-box swiper-container">
                        <div class="swiper-wrapper">
                            <div class="swiper-slide">
                                <a href="#">
                                    <p class="s_name s_name3">游戏代练</p>
                                    <p class="s_title ofh">魔兽世界</p>
                                    <p class="s_text ofh">【当面交易】2260万金币=43元</p>
                                    <p class="s_text1 ofh">【在线发货，方便快捷】</p>
                                    <p class="s_exp ofh">1元=2857.14金游戏币</p>
                                    <img src="/public/images/index/game_bar.png" width="140" height="140" alt="">
                                </a>
                            </div>
                            <div class="swiper-slide">
                                <a href="#">
                                    <p class="s_name s_name3">游戏代练</p>
                                    <p class="s_title ofh">魔兽世界</p>
                                    <p class="s_text ofh">【当面交易】2260万金币=43元</p>
                                    <p class="s_text1 ofh">【在线发货，方便快捷】</p>
                                    <p class="s_exp ofh">1元=2857.14金游戏币</p>
                                    <img src="/public/images/index/game_bar.png" width="140" height="140" alt="">
                                </a>
                            </div>
                            <div class="swiper-slide">
                                <a href="#">
                                    <p class="s_name s_name3">游戏代练</p>
                                    <p class="s_title ofh">地下城与勇士</p>
                                    <p class="s_text ofh">【当面交易】2260万金币=43元</p>
                                    <p class="s_text1 ofh">【在线发货，方便快捷】</p>
                                    <p class="s_exp ofh">1元=2857.14金游戏币</p>
                                    <img src="/public/images/index/game_bar.png" width="140" height="140" alt="">
                                </a>
                            </div>
                            <div class="swiper-slide">
                                <a href="#">
                                    <p class="s_name s_name3">游戏代练</p>
                                    <p class="s_title ofh">魔兽世界</p>
                                    <p class="s_text ofh">【当面交易】2260万金币=43元</p>
                                    <p class="s_text1 ofh">【在线发货，方便快捷】</p>
                                    <p class="s_exp ofh">1元=2857.14金游戏币</p>
                                    <img src="/public/images/index/game_bar.png" width="140" height="140" alt="">
                                </a>
                            </div>
                        </div>
                        <!-- 如果需要分页器 -->
                        <div class="swiper-pagination"></div>
                        <!-- 如果需要导航按钮 -->
                        <div class="swiper-button-prev"></div>
                        <div class="swiper-button-next"></div>
                    </div>
                </li>
            </ul>
        </div>

        <!--    一级广告位    -->
        <div class="cd1"><img src="/public/images/index/ad1.png" alt=""></div>

        <!--     商品推荐     -->
        <div class="recommend">
            <div class="broadcast_title cf"><p class="fl pr">商品推荐<span class="line_l"></span></p><a class="fr" href="javascript:void(0);">更多</a></div>
            <ul class="broadcast_ul recommend_ul cf">
                <li class="fl pr"><a class="li_a" href="#"><p class="text_c"><img class="dib" src="/public/images/index/shop.png" alt=""></p><p class="re_text ofh">1919酒类直供奔富BIN407解 百纳赤霞珠红葡萄酒 红酒</p><p class="re_money ofh">658平台币</p><p class="re_stock ofh">剩余库存：188支</p></a><a class="ex_a" href="javascript:void(0);">立即兑换</a></li>
                <li class="fl pr"><a class="li_a" href="#"><p class="text_c"><img class="dib" src="/public/images/index/shop.png" alt=""></p><p class="re_text ofh">1919酒类直供奔富BIN407解 百纳赤霞珠红葡萄酒 红酒</p><p class="re_money ofh">658平台币</p><p class="re_stock ofh">剩余库存：188支</p></a><a class="ex_a" href="javascript:void(0);">立即兑换</a></li>
                <li class="fl pr"><a class="li_a" href="#"><p class="text_c"><img class="dib" src="/public/images/index/shop.png" alt=""></p><p class="re_text ofh">1919酒类直供奔富BIN407解 百纳赤霞珠红葡萄酒 红酒</p><p class="re_money ofh">658平台币</p><p class="re_stock ofh">剩余库存：188支</p></a><a class="ex_a" href="javascript:void(0);">立即兑换</a></li>
                <li class="fl pr"><a class="li_a" href="#"><p class="text_c"><img class="dib" src="/public/images/index/shop.png" alt=""></p><p class="re_text ofh">1919酒类直供奔富BIN407解 百纳赤霞珠红葡萄酒 红酒</p><p class="re_money ofh">658平台币</p><p class="re_stock ofh">剩余库存：188支</p></a><a class="ex_a" href="javascript:void(0);">立即兑换</a></li>
            </ul>
        </div>

    </div>

    <?php load_view("inc/footer");?>

<script src="/public/js/jquery.ext.js"></script>
<script src="/public/js/swiper-4.3.3.min.js"></script>
<script src="/public/js/index.js"></script>
<script>
    $(function(){
        //轮播图
        //banner
        $(".slide-box").hbySlide();
    });

    var mySwiper = new Swiper ('.swiper-container', {
        direction: 'horizontal',
        autoplay: false,
        loop: true,
        navigation: {
            nextEl: '.swiper-button-next',
            prevEl: '.swiper-button-prev',
        },

        // 如果需要分页器
        pagination: {
            el: '.swiper-pagination',
        }
    })
</script>
</body>
</html>