<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="content-type" content="text/html">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>当前列表</title>
    <meta name="keywords" content="">
    <meta name="description" content="">
    <link rel="stylesheet" href="/public/css/base.css">
    <link rel="stylesheet" href="/public/css/public.css">
    <link rel="stylesheet" href="/public/css/index_more.css">
</head>
<body class="homeMain">

    <?php load_view("inc/header");?>
    <!--        content        -->
    <div class="content_box container">
        <div class="crumbs">您的位置：<span>首页></span><span>当前列表</span></div>
        <div class="game_box">
            <div class="game_tap cf">
                <?php foreach ($nav as $k=>$v): ?>
                    <?php if($k == 0): ?>
                        <a class="fl tap_a active" href="javascript:void(0)" data-gid="<?=$v['id']?>"><?=$v['type']?></a>
                    <?php else: ?>
                        <a class="fl tap_a" href="javascript:void(0)" data-gid="<?=$v['id']?>"><?=$v['type']?></a>
                    <?php endif; ?>
                <?php endforeach; ?>
            </div>
            <div class="game_content">

                <ul class="game_ul cf active" id="gamecontent">
                    <?php foreach ($game as $kg=>$kv): ?>
                    <li class="fl">
                        <a href="/List/index?type=index&apkname=<?=$kv['title']?>&shoptype=all">
                            <img src="http://www.zhishengwh.com/uploads/<?=$kv['icon']?>" width="120" height="120" alt="<?=$kv['title']?>">
                            <p class="game_name"><?=$kv['title']?></p>
                        </a>
                    </li>
                    <?php endforeach; ?>
                </ul>

            </div>
        </div>

    </div>

    <?php load_view("inc/footer");?>

    <script src="/public/js/index_more.js"></script>
</body>
</html>