<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="content-type" content="text/html">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>金币交易</title>
    <meta name="keywords" content="">
    <meta name="description" content="">
    <link rel="stylesheet" href="/public/css/base.css">
    <link rel="stylesheet" href="/public/css/public.css">
    <link rel="stylesheet" href="/public/css/details.css">
    <link rel="stylesheet" href="/public/css/shop_details.css">
</head>
<body>
    <!--    公共头部    -->
    <?php load_view("inc/header");?>

    <!--    content    -->
    <div class="content_box container">

        <!--  导航栏  -->
        <div class="common_nav_bar">
            <a class="sub_bar" href="javascript:void(0)">首页</a> &gt;
            <a class="sub_bar" href="javascript:void(0)">兑换中心</a> &gt;
            <a class="sub_bar" href="javascript:void(0)">商品交易</a>
        </div>

        <!--   商品介绍部分   -->
        <div class="goods_box cf">
            <div class="goods_left fl">
                <div class="goods_big"><img src="/public/images/shop_details/goodsBig.png" height="540" width="540" alt=""></div>
                <div class="goods_little_box cf">
                    <img class="fl sub_little_box active" src="/public/images/shop_details/goodsBig.png" alt="">
                    <img class="fl sub_little_box" src="/public/images/shop_details/goodsLittle2.png" alt="">
                    <img class="fl sub_little_box" src="/public/images/shop_details/goodsLittle2.png" alt="">
                    <img class="fl sub_little_box" src="/public/images/shop_details/goodsLittle2.png" alt="">
                </div>
            </div>
            <div class="goods_right fl">
                <div class="goods_name ofh" title="皇冠手镯TG3TZ0007">皇冠手镯TG3TZ0007</div>
                <div class="goods_explain">备注：兑换中可能会出现商品已经兑换完</div>
                <div class="good_grey_box">
                    <div class="goods_grey_top cf">
                        <div class="cf sub_goods_grey fl"><p class="goods_tit fl">商品价格：</p><p class="fl now_price">￥<span class="goods_price">199</span></p><p class="fl last_price">￥<span>210</span></p></div>
                        <div class="cf sub_goods_grey fl"><p class="goods_tit fl">商品运费：</p><p class="fl clothes ofh">到付（顺丰到付）或者自取</p></div>
                        <div class="cf sub_goods_grey fl"><p class="goods_tit fl">商品类型：</p><p class="fl clothes ofh">玩家兑换</p></div>
                    </div>
                    <div class="goods_grey_bottom cf">
                        <div class="cf sub_goods_grey goods_g fl"><div class="goods_tit fl">商品规格：</div><p class="fl ofh"><span>皇冠手镯19.37g</span></p></div>
                        <div class="cf sub_goods_grey goods_g fl"><div class="goods_tit fl">兑换数量：</div><p class="fl ofh"><span>只能兑换一种</span></p></div>
                        <div class="cf sub_goods_grey goods_g fl"><div class="goods_tit fl">商品颜色：</div><p class="fl ofh"><span>黄金金色</span></p></div>
                        <div class="cf sub_goods_grey goods_g fl"><div class="goods_tit fl">商品库存：</div><p class="fl ofh"><span>117件</span></p></div>
                    </div>
                </div>
                <div class="operate_box cf">
                    <a class="btn_buy fl" href="order.html">立即购买</a>
                    <a class="btn_add_cart fl" href="javascript:void(0)">咨询客服</a>
                    <a class="btn_fav fl" href="javascript:void(0)"><i></i>收藏</a>
                </div>
            </div>
        </div>

        <!--   商品详情部分   -->
        <div class="detail_box cf">
            <div class="detail_left fl">
                <div class="detail_tab cf">
                    <a class="sub_detail_tab active" href="javascript:void(0)">详情</a>
                </div>
                <div class="detail_con detail_li active">
                    <div class="sub_detail_con">
                        <div class="specifications">
                            <ul class="cf">
                                <li class="fl"><span>商品编号：</span><span>DB059-20180805-13871955</span></li>
                                <li class="fl"><span>商品类型：</span><span>游戏帐号</span></li>
                                <li class="fl"><span>发布时间：</span><span>2018-09-25 04:04:15</span></li>
                                <li class="fl"><span>到期时间：</span><span>2018-10-24 04:04:15</span></li>
                            </ul>
                            <div class="parameter">
                                <span>商品描述：</span>
                                <p>17094★大象专卖★十年老店★，欢迎光临本工作室。平价销售，谢绝议价</p>
                                <p>1.本店七年专注出售地下城与勇士(DNF)账号，本店为5173签约店铺，已缴纳万元保证金，万笔账号销售无一差评，销售了七年DNF账号，好评率百分之百，没有必要为了找回一个帐号而毁了信誉。</p>
                                <p>2.交易成功后请找客服要店主身份证，电话，QQ，账号有任何问题直接联系本店，本店郑重承诺，出现问题的账号本店愿意全额退款，终身售后。</p>
                                <p>3.本店售出的账号，本店可以高价回收。</p>
                                <p>4.本店出售的账号截图因为限制问题，只能截图5张，所以购买之后肯定会有惊喜，只要截图的肯定都有，截图后我们不会再上帐号，没有截图的也可能有极品装备。有些号没加点所以面板偏低</p>
                                <p>5本店帐号都是无QQ好友，无2级，无仓库密码</p>
                            </div>
                        </div>
                        <div class="seller">
                            <div class="broadcast_title cf">
                                <p class="fl pr"><i class="fl"></i>实物兑换详情图（最终于实物图为准）</p>
                            </div>
                            <div class="seller_box">
                                <img src="/public/images/shop_details/detailImg.png" alt="">
                                <img src="/public/images/shop_details/detailImg2.png" alt="">
                                <img src="/public/images/shop_details/detailImg3.png" alt="">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="detail_right fl cf">
                <div class="tit fl">浏览记录</div>
                <div class="con fl">
                    <ul class="cf">
                        <li class="fl sub_goods_box copy" data-num="5">
                            <p class="goods_box_name"><i class="dib"></i>【跨1华南区 大暗黑天 男 90级 QQ等级19级 无QQ好友 不存在5天封号记录 】天帝星辰套+三神器+11氤氲之息+红字</p>
                            <p class="goods_box_price">￥<span>239</span></p>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>


    <!--    底部公共    -->
    <?php load_view("inc/footer");?>

    <script src="/public/js/jquery.js"></script>
    <script src="/public/js/public.js"></script>
    <script src="/public/js/shop_details.js"></script>
</body>
</html>